language: node_js

node_js:
  - "iojs"

before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo apt-add-repository "deb http://dl.google.com/linux/chrome/deb/ stable main"
  - sudo sed -i s/deb-src.*google.*//g /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g grunt-cli bower
  - npm install coveralls
  - npm install
  - bower install

before_script:
  - grunt serve &
  - sleep 3

after_success:
  - cat ./coverage/server/lcov.info ./coverage/client/lcov.info | ./node_modules/coveralls/bin/coveralls.js
